; ============================================================
; DUINO-COIN - MULTI ESP PLATFORMIO
; ============================================================

[platformio]
src_dir = ESP_Code


; ============================================================
; SETTING UMUM
; ============================================================

[env]
framework = arduino
monitor_speed = 500000

lib_deps =
    bblanchon/ArduinoJson


; ============================================================
; ESP32 CLASSIC
; ESP32-WROOM-32
; ESP32 DevKit V1
; ============================================================

[env:ESP32]
platform = espressif32
board = esp32dev


; ============================================================
; ESP32-C3
; ESP32-C3 SuperMini
; ESP32-C3 DevKitM-1
; ============================================================

[env:ESP32-C3]
platform = espressif32
board = esp32-c3-devkitm-1

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1


; ============================================================
; ESP32-S2
; ============================================================

[env:ESP32-S2]
platform = espressif32
board = esp32-s2-saola-1

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=0


; ============================================================
; ESP32-S3
; ============================================================

[env:ESP32-S3]
platform = espressif32
board = esp32-s3-devkitc-1

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1


; ============================================================
; ESP-12F / ESP-12E STANDALONE
; ESP8266MOD
; ============================================================

[env:ESP-12F]
platform = espressif8266
board = esp12e
board_build.f_cpu = 160000000L
build_flags =
    -O3


; ============================================================
; ESP8266 - NodeMCU 1.0
; ESP-12E / ESP-12F yang terpasang di board NodeMCU
; ============================================================

[env:ESP8266-NodeMCU]
platform = espressif8266
board = nodemcuv2


; ============================================================
; ESP8266 - Wemos D1 Mini
; ============================================================

[env:ESP8266-D1-Mini]
platform = espressif8266
board = d1_mini
board_build.f_cpu = 160000000L
build_flags =
    -O3


; ============================================================
; ESP8266 - Wemos D1 R1
; ============================================================

[env:ESP8266-D1]
platform = espressif8266
board = d1


; ============================================================
; ESP8266 - NodeMCU 0.9 lama
; ============================================================

[env:ESP8266-NodeMCU-Old]
platform = espressif8266
board = nodemcu
