[platformio]
src_dir = ESP_Code

[env:ESP8266-D1-Mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 500000
lib_deps = bblanchon/ArduinoJson

[env:ESP-12F]
platform = espressif8266
board = esp12e
framework = arduino
board_build.f_cpu = 160000000L
monitor_speed = 500000
lib_deps = bblanchon/ArduinoJson
build_flags = -O3
